name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - azure  # Trigger the workflow on push to the azure branch
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - azure  # Trigger on pull requests targeting the azure branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Replace with your Node.js version if needed

      # Step 4: Install dependencies and build
      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # Adjust to your build command (e.g., `npm run build`)

      # Step 5: Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"  # Adjust if your app is in a subfolder (e.g., `src` or `public`)
          api_location: ""   # Leave empty if you don't have an API directory
          output_location: "build"  # Adjust to the output folder where your app is built (e.g., `build` or `dist`)
