name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}

      # Step 3: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # 
